language: python
python:
- '3.6'
cache: pip
node_js: 6
env:
  global:
  - AWS_DEFAULT_REGION: us-east-1
  - secure: WT32ZRymO47CKaHDWhrBqv3eBFWPJnNpxxl8Yv7vdyaQCRzP5PIAoLrfyx/BY7ODLvvF2SjK12ncVlljYlt9tx7sjvom//EKu5kIyic3o8gn82E2rsK23cEek3RR3BvRvydkldZWW/9l81X8sXxvAL4LN4Dp0NpS3shFPQqf3SskXe4aij4SjI65MBaBZc+gIOSiJLmgv+I780h/HWFLyG4yo2gTOiYN3kBoIWoyiJq/7AWJz0jlKWAujHgNB0SOrAcuTZ2C7hr2xQwoYhm3CEeVxv42KJP+qmD+Xkfa7QW+OkRwLJA9JKEDtf28Y9Bm6rKbBSvqSjYtIDMvT7j8S/DV04icauBkmzRZbDfSpWQcB0LYqOhhDekj6DC9lEm+kUCZ4G5s/0jhhEsDxUZ6vl0xTholdd6HmRuSFK0OiSregLBNSwj+diM3oy3+HgaEy0lKDLLzc8klqPZnEdoiCOjbIPo4+6kjUSbOnsH+qVPGet88/tYci0Itk7Qewsmd4Enu3DYLS9NBFGU9+2TULvPDA8XZZP5i19DYRSB03jDdCVnoQS8uKs3sLBaB1RBMM9EXieaacKK6KfmePfOhuZcQxRyflZcElSH3kGdG8pfstbLfjG0NW1Z8EVL1o6fkZUNbrqBBaAw9T1sjZM7mfpdSACUbJdaz1wIXjnvgylI=
  - secure: Ty6Z+aKOr/E8FDvw7ckobGkUsIf6Rl9OnC90u6ImBqCEeQYWoRIgLoqeSfq9sXJGqSzd6VreLLaVc3hZJEEWBCcLIcq0j+MpeOm+rL4hfN8Tht2mjSriMvbeQqgk280u4Gfk0UiW6SUxYtu/L5vQTdfMQ5Qgm6ssdT5oK5ZNiIAI7MPBHW2fDZ8NW3rJgf9xH3FCCEE4TsBcAS9s82ev92uliRePcA06WKa9ERB2jxNJNlX7ey40+6x4ZMnW3nL2yWDqHewFSddZGMKaocsK1lGSwmf8Hyskyjqj5hgUROxaTFQHnF5KjDHipuJnzmAVEkXfQA28rs0GAeAxTNsdGqUyqq0ElXjVNH/86HJed4Sk/lNKxQmyVbotfMLLU2pfK69fyRQM1ZoS+p34WTF0fgANflUmWchch5xlnZ962vEApSTbYTL6sbD/Fajd+dKRpCV0W42OzQZWg1EXjJeFG857wlhPRjd6N1p/ga/a+Ci9KwGHrysBA6tqGvG/HNnAvj7k9nhqQBvW5rcohs+xaWNsiFjqg9RVCyotB9+EvkUhiEkbuvp2mF2xTJ86/j9aDkK1dSoGT1+DrTF87S8CxnyZWBmK90zhk+D5MUd7P/6Fyk4/L3MFNkk0yRBa+2yU9gn929wClrD2a0H+TzoKk89D3lchjlgS0fsvMLDGIx0=
notifications:
  slack:
    secure: HJHvn6wKNCIr3skGWx2HK8gz9KIdg8Yd73gBoUTyUgz39v16WkISHOVsSDDTg4RunX/nggO5XBwjc9HwZeiX2V4OjzAukOaufk/OOvz2Hl4vhkUIJWgho3KFJAcm+dOi3wwJHGFBtLW3yvprEnjIf6MQoQqsnXK21nzihgvO1kBS8UYagJvtFf0Tqhz3Biz1lcEJi5cTpkfaG9fCBit4qzQig5jZeBiVb2/aKiQYDhAvc6O9VijJj8TCCPWhPpQGAOUR+yjKZQGnSTmSEU1iJbvEngpmliARP3vAUS28Ahrw84C0LchdgBA3E1LcKxjZokRfaxKAHMEWg69ovufrwLoo6Eb6vLQR3qhvDrwrPV3zG7kgiiRStxtz2mjeAljcLqoKQ0BrUNxEEF4bHyVVAc5zpIalIWD/YzUw+WOrMcAA+Oti4XAbuD7tSoZrkqCutBmxonHLjITatGMzndKBMhHIJu5v7y77ibX1ZyRixBqZ/B9v+0HOEn61nZErlpy0L+TMRX/bWPyOFMqAQO6gz1mnEwwSeU/HBs020/yGrcAWCjU8bCukOJ8ax4fIpOSPgU3tKc5759I3YOE3s+QM4TWZ97CHk54c9t2nvW6sE0mZdjSIjVMW/5Rq4a9CIJaYnvgKjGgzq+rqlSugOxZL95gqBwQLqt3iHmpjNB54pto=
before_install:
- openssl aes-256-cbc -K $encrypted_5ae27258bb12_key -iv $encrypted_5ae27258bb12_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- pip install -U pip
- pip install awscli
stages:
- name: Dev
  if: type = pull_request
- name: Prod
  if: type = push AND branch = master
jobs:
  include:
  - stage: Dev
    script:
    - npm install
    - npm run build:dev
    - aws s3 sync build/ s3://dev.timereport.codelabs.se --acl public-read
  - stage: Prod
    on:
      branch: master
    script:
    - npm install
    - npm run build:prod
    - aws s3 sync build/ s3://timereport.codelabs.se --acl public-read
