language: python
python:
- '3.6'
install: true
cache: pip
node_js: 6
env:
  global:
  - AWS_DEFAULT_REGION: us-east-1
  - secure: WT32ZRymO47CKaHDWhrBqv3eBFWPJnNpxxl8Yv7vdyaQCRzP5PIAoLrfyx/BY7ODLvvF2SjK12ncVlljYlt9tx7sjvom//EKu5kIyic3o8gn82E2rsK23cEek3RR3BvRvydkldZWW/9l81X8sXxvAL4LN4Dp0NpS3shFPQqf3SskXe4aij4SjI65MBaBZc+gIOSiJLmgv+I780h/HWFLyG4yo2gTOiYN3kBoIWoyiJq/7AWJz0jlKWAujHgNB0SOrAcuTZ2C7hr2xQwoYhm3CEeVxv42KJP+qmD+Xkfa7QW+OkRwLJA9JKEDtf28Y9Bm6rKbBSvqSjYtIDMvT7j8S/DV04icauBkmzRZbDfSpWQcB0LYqOhhDekj6DC9lEm+kUCZ4G5s/0jhhEsDxUZ6vl0xTholdd6HmRuSFK0OiSregLBNSwj+diM3oy3+HgaEy0lKDLLzc8klqPZnEdoiCOjbIPo4+6kjUSbOnsH+qVPGet88/tYci0Itk7Qewsmd4Enu3DYLS9NBFGU9+2TULvPDA8XZZP5i19DYRSB03jDdCVnoQS8uKs3sLBaB1RBMM9EXieaacKK6KfmePfOhuZcQxRyflZcElSH3kGdG8pfstbLfjG0NW1Z8EVL1o6fkZUNbrqBBaAw9T1sjZM7mfpdSACUbJdaz1wIXjnvgylI=
  - secure: Ty6Z+aKOr/E8FDvw7ckobGkUsIf6Rl9OnC90u6ImBqCEeQYWoRIgLoqeSfq9sXJGqSzd6VreLLaVc3hZJEEWBCcLIcq0j+MpeOm+rL4hfN8Tht2mjSriMvbeQqgk280u4Gfk0UiW6SUxYtu/L5vQTdfMQ5Qgm6ssdT5oK5ZNiIAI7MPBHW2fDZ8NW3rJgf9xH3FCCEE4TsBcAS9s82ev92uliRePcA06WKa9ERB2jxNJNlX7ey40+6x4ZMnW3nL2yWDqHewFSddZGMKaocsK1lGSwmf8Hyskyjqj5hgUROxaTFQHnF5KjDHipuJnzmAVEkXfQA28rs0GAeAxTNsdGqUyqq0ElXjVNH/86HJed4Sk/lNKxQmyVbotfMLLU2pfK69fyRQM1ZoS+p34WTF0fgANflUmWchch5xlnZ962vEApSTbYTL6sbD/Fajd+dKRpCV0W42OzQZWg1EXjJeFG857wlhPRjd6N1p/ga/a+Ci9KwGHrysBA6tqGvG/HNnAvj7k9nhqQBvW5rcohs+xaWNsiFjqg9RVCyotB9+EvkUhiEkbuvp2mF2xTJ86/j9aDkK1dSoGT1+DrTF87S8CxnyZWBmK90zhk+D5MUd7P/6Fyk4/L3MFNkk0yRBa+2yU9gn929wClrD2a0H+TzoKk89D3lchjlgS0fsvMLDGIx0=
notifications:
  slack:
    secure: XiGOBAIIGUqslYcjTddiBku5eyi9MaEl5SwGY1iuJ3OFKC/P7gFjHlaSh90MSvrHbS5tg/bkOXYf59DUPl5IJinFJebzdpr12+ei/YOORiV/UCUFCucVjEqcT/1qJ212NZ4A4wT+ZyU/H5bbYclhaq41TPFtjmPcOUkrysfBpC+ofz3MM/1lZUXp5vJ8mETtjc7w70cDnuPxVtWeup7uUxcl4nDBRykmKOJ8BJ1vtpwGvUwFCf+glC6gUDmAQLnDpNArDARIGNqIdYSrb3pVLIkW7Fcj8EB6HCYjAve6kME/4DmfQf9hJWQkiES5UZlufUYh7nVmT6sJKR2bPDWJL6H52xsERxmM86rtLex7tA0y0ROswAToAFK7vh1wpbiqGDbC17WLbGGIH0W5n7O4T0W3iFfA+63/hqqNNfvFfvKaLWFxjmv9Qmf1nF8vpMusoNqZADzj8mPVEDJPNFErRjCqjfi/ZzVQ15+2PRECTauNfHpv/vDgupRVisF0WuTAacu3k7jEVjaaNWB9Z1eF7v3IBPJb2HwqNISynsBBgIo6oHWGyd9FtuVpOhOUHNjKyEs/hxBrA1sFM5CKgMqT4WGuWtgRJhf7+3WbXUZBigwdxQCWfbNlOvjkwhBca7qTijDDmLxmipmyH7YRdS8uI3SwVkVC0KUHlLKjCTGhHs4=
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- pip install -U pip
- pip install awscli
stages:
- name: Dev
  if: type = push
- name: Prod
  if: type = push AND branch = master
jobs:
  include:
  - stage: Dev
    script:
    - npm install
    - npm run build:dev
    - aws s3 sync build/ s3://dev.timereport.codelabs.se --acl public-read
  - stage: Prod
    on:
      branch: master
    script:
    - npm install
    - npm run build:prod
    - aws s3 sync build/ s3://timereport.codelabs.se --acl public-read
