name: Node 12
on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: 12

    steps:
      - uses: actions/checkout@v2
      - name: Setup ENV
        run: |
          echo $REACT_APP_BACKEND_URL > .env.prod
          echo $REACT_APP_GOOGLE_CLIENT_ID >> .env.prod
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_PROD_BACKEND_URL }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_PROD_GOOGLE_CLIENT_ID }}

      - name: Setup node dev
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build:prod
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read 
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'
