name: Node 12
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ENV
        run: |
          echo REACT_APP_backend_url=$backend_url_prod > ./.env.prod
          echo REACT_APP_google_client_id=$google_client_id_prod >> ./.env.prod
        env:
          backend_url_prod: ${{ secrets.BACKEND_URL_PROD }}
          google_client_id_prod: ${{ secrets.GOOGLE_CLIENT_ID_PROD }}

      - name: Setup node instance
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run build:prod

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read 
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'
